### ISSUE TITLE
[FR] Provide secondary and tertiary label

### ISSUE THREAD

**Issue by steezieV** [sandstorm/LazyDataSource#1]
Hi!

Would it be possible to include the secondary and tertiary labels which are available in the regular SelectBoxEditor?

![image](https://user-images.githubusercontent.com/125565479/219423988-175b50e6-0e5a-4cf5-b03e-b19036e3ff45.png)

**Comment by skurfuerst** [comment]
good idea :) I cannot promise when I can work on this, though, but pull requests would be gladly accepted ❤️

**Comment by steezieV** [comment]
Hi @skurfuerst,

Thanks for the reply! We could try to do it ourselves if you could point us in the right direction. Unfortunately we don't have a lot of experience with React and the Neos UI Extensibility so it's hard to understand what's happening in the code.

**Comment by christoph-daehne** [comment]
In the React-part of the implementation the options from your DataProvider are passed directly to the _(Multi)SelectBox_ from Neos. I am not fully sure about the internals, but one of two inner components in the SelectBox does render the props
* label
* secondaryLabel
* tertiaryLabel

See https://github.com/neos/neos-ui/blob/8.3/packages/react-ui-components/src/SelectBox_Option_MultiLineWithThumbnail/selectBox_Option_MultiLineWithThumbnail.js

Chances are good that you can set those labels in your custom DataProvider for all options and they appear in the UI. If you try it out, please reply back your results ;)

**Comment by Nickosaurus** [comment]
Hi @christoph-daehne,

sorry for our late reply, but things/life got in the way ;)... 

That is what we thought too, but unfortunately it does not work. I am currently on it and I already added "ListPreviewElement={PreviewOption}" within the Editor, which I thought would do the trick, but that alone is not sufficient...

Debugging continues, but any suggestions are welcome. Once we figure it out, we will submit our pull request. 

P.s. We plan to extend the LazyDataSource so that one has the option to specify if the List should be initialized with some default items even before an entry was selected or a search term was issued. As an example: Display the most recent 10 Items (as this is what our editors use most often). We would implement it within the trait as additional optional option, so that it is none breaking - what do you think?
